Add linting & unit tests to pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -14,5 +14,16 @@ then
     echo "Aborting commit due to whitespace errors."
     exit 1
 else
-    npm test
+    # Fail on first line that fails.
+    set -e
+
+    NEW_FILES=$(git --no-pager diff --name-only --cached)
+    JS_FILES=$(echo "$NEW_FILES" | { grep *.js || true; })
+
+    if [ -n "$JS_FILES" ];
+    then
+        npm run linter:js -s -- $JS_FILES
+        npm run test -s;
+        exit 0
+    fi
 fi
